In [114]:
import numpy as np
import pandas as pd 


In [115]:
data = pd.read_table('housing.data',header=None,delim_whitespace=True)
data = np.array(data)
label = data[:, 13:14]
feature = data[:, 0:13]
#print(data[:, 0])
#print (label)
print(feature)
#print(data.shape[1])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [116]:
#pearson linear correlation
plcs = []
y = data[:,-1]

for i in range((data.shape[1]-1)):
    x = data[:,i]
    plc = np.corrcoef(x, y)
    #print(plc)
    plcs.append(plc[0,1])

print(plcs)


[-0.3883046085868113, 0.36044534245054277, -0.4837251600283727, 0.17526017719029854, -0.42732077237328264, 0.6953599470715395, -0.3769545650045963, 0.24992873408590388, -0.38162623063977763, -0.468535933567767, -0.5077866855375617, 0.33346081965706653, -0.7376627261740147]


In [117]:
#归一化处理
feature = (feature - feature.mean(axis=0)) / feature.std()
#print(feature.mean(axis=0))
#print(feature - feature.mean(axis=0))

#print(feature)

[3.61352356e+00 1.13636364e+01 1.11367787e+01 6.91699605e-02
 5.54695059e-01 6.28463439e+00 6.85749012e+01 3.79504269e+00
 9.54940711e+00 4.08237154e+02 1.84555336e+01 3.56674032e+02
 1.26530632e+01]
[[ -3.60720356   6.63636364  -8.82677866 ...  -3.1555336   40.22596838
   -7.67306324]
 [ -3.58621356 -11.36363636  -4.06677866 ...  -0.6555336   40.22596838
   -3.51306324]
 [ -3.58623356 -11.36363636  -4.06677866 ...  -0.6555336   36.15596838
   -8.62306324]
 ...
 [ -3.55276356 -11.36363636   0.79322134 ...   2.5444664   40.22596838
   -7.01306324]
 [ -3.50393356 -11.36363636   0.79322134 ...   2.5444664   36.77596838
   -6.17306324]
 [ -3.56611356 -11.36363636   0.79322134 ...   2.5444664   40.22596838
   -4.77306324]]
